# Generated by Django 4.2.24 on 2025-09-20 01:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo Atual",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo do Usuário",
                "verbose_name_plural": "Saldos dos Usuários",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="BalanceHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("ADD", "Adição"),
                            ("SUBTRACT", "Subtração"),
                            ("SET", "Definição"),
                            ("RESET", "Reset"),
                        ],
                        max_length=10,
                        verbose_name="Operação",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "previous_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Anterior"
                    ),
                ),
                (
                    "new_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Novo Saldo"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "user_balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="finance.userbalance",
                        verbose_name="Saldo do Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Saldo",
                "verbose_name_plural": "Históricos de Saldo",
                "ordering": ["-created_at"],
            },
        ),
    ]
