# Generated by Django 4.2.24 on 2025-09-20 02:13

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "icon",
                    models.CharField(default="💰", max_length=50, verbose_name="Ícone"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Cor em hexadecimal (#RRGGBB)",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Receita"),
                            ("EXPENSE", "Despesa"),
                            ("BOTH", "Ambos"),
                        ],
                        default="BOTH",
                        max_length=10,
                        verbose_name="Tipo de Categoria",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Categorias padrão do sistema",
                        verbose_name="Categoria Padrão",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se vazio, é uma categoria padrão do sistema",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("INCOME", "Receita"), ("EXPENSE", "Despesa")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Subcategoria"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Data da Transação"
                    ),
                ),
                (
                    "receipt",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="receipts/%Y/%m/",
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="É Recorrente"),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Não recorrente"),
                            ("DAILY", "Diário"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensal"),
                            ("YEARLY", "Anual"),
                        ],
                        default="NONE",
                        max_length=10,
                        verbose_name="Tipo de Recorrência",
                    ),
                ),
                (
                    "recurrence_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Final da Recorrência"
                    ),
                ),
                (
                    "balance_updated",
                    models.BooleanField(default=False, verbose_name="Saldo Atualizado"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "parent_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_transactions",
                        to="finance.transaction",
                        verbose_name="Transação Pai",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "transaction_date"],
                        name="finance_tra_user_id_bed389_idx",
                    ),
                    models.Index(
                        fields=["user", "transaction_type"],
                        name="finance_tra_user_id_75a566_idx",
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="finance_tra_user_id_be5f56_idx",
                    ),
                ],
            },
        ),
    ]
