# Generated by Django 4.2.24 on 2025-09-24 18:27

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "game_start_date",
                    models.DateField(
                        default=datetime.date(2025, 1, 1),
                        verbose_name="Data de Início do Jogo",
                    ),
                ),
                (
                    "current_game_date",
                    models.DateField(
                        default=datetime.date(2025, 1, 1),
                        verbose_name="Data Atual do Jogo",
                    ),
                ),
                (
                    "game_end_date",
                    models.DateField(
                        default=datetime.date(2026, 1, 1),
                        verbose_name="Data de Fim do Jogo",
                    ),
                ),
                (
                    "session_start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Hora de Início da Sessão",
                    ),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Última Atualização",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("PAUSED", "Pausado"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Falhou"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="Status do Jogo",
                    ),
                ),
                (
                    "time_acceleration",
                    models.IntegerField(
                        default=1440,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10080),
                        ],
                        verbose_name="Aceleração do Tempo (minutos por dia)",
                    ),
                ),
                (
                    "total_score",
                    models.IntegerField(default=0, verbose_name="Pontuação Total"),
                ),
                (
                    "days_survived",
                    models.IntegerField(default=0, verbose_name="Dias Sobrevividos"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_session",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Jogo",
                "verbose_name_plural": "Sessões de Jogo",
                "ordering": ["-last_update_time"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "icon",
                    models.CharField(
                        default="shopping-cart", max_length=50, verbose_name="Ícone"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Cor"
                    ),
                ),
                (
                    "profit_margin_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=5,
                        verbose_name="Margem de Lucro Mínima (%)",
                    ),
                ),
                (
                    "profit_margin_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        max_digits=5,
                        verbose_name="Margem de Lucro Máxima (%)",
                    ),
                ),
                (
                    "shelf_life_min",
                    models.IntegerField(
                        default=1, verbose_name="Validade Mínima (dias)"
                    ),
                ),
                (
                    "shelf_life_max",
                    models.IntegerField(
                        default=30, verbose_name="Validade Máxima (dias)"
                    ),
                ),
                (
                    "seasonal_demand_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=3,
                        verbose_name="Multiplicador de Demanda Sazonal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Produto",
                "verbose_name_plural": "Categorias de Produtos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupermarketBalance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000.00"),
                        max_digits=12,
                        verbose_name="Saldo Atual",
                    ),
                ),
                (
                    "minimum_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        max_digits=12,
                        verbose_name="Saldo Mínimo",
                    ),
                ),
                (
                    "bankruptcy_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Limite de Falência",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "game_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supermarket_balance",
                        to="game.gamesession",
                        verbose_name="Sessão de Jogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo do Supermercado",
                "verbose_name_plural": "Saldos dos Supermercados",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="BalanceHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("ADD", "Adição"),
                            ("SUBTRACT", "Subtração"),
                            ("SET", "Definição"),
                            ("RESET", "Reset"),
                            ("SALE", "Venda"),
                            ("PURCHASE", "Compra"),
                            ("SALARY", "Pagamento de Salário"),
                            ("RENT", "Aluguel"),
                            ("UTILITY", "Contas"),
                        ],
                        max_length=10,
                        verbose_name="Operação",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "previous_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Anterior"
                    ),
                ),
                (
                    "new_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Novo Saldo"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "game_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Data do Jogo"
                    ),
                ),
                (
                    "supermarket_balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="game.supermarketbalance",
                        verbose_name="Saldo do Supermercado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Saldo",
                "verbose_name_plural": "Históricos de Saldo",
                "ordering": ["-created_at"],
            },
        ),
    ]
