# Generated by Django 4.2.24 on 2025-09-24 18:41

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Preço de Compra",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Preço de Venda",
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Estoque Atual",
                    ),
                ),
                (
                    "min_stock",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Estoque Mínimo",
                    ),
                ),
                (
                    "max_stock",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Estoque Máximo",
                    ),
                ),
                (
                    "shelf_life_days",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Validade (dias)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_promotional",
                    models.BooleanField(default=False, verbose_name="Em Promoção"),
                ),
                (
                    "promotional_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Preço Promocional",
                    ),
                ),
                (
                    "promotional_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Início da Promoção"
                    ),
                ),
                (
                    "promotional_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim da Promoção"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="game.productcategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pessoa de Contato"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Endereço")),
                (
                    "delivery_time_days",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Prazo de Entrega (dias)",
                    ),
                ),
                (
                    "minimum_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=12,
                        verbose_name="Valor Mínimo do Pedido",
                    ),
                ),
                (
                    "reliability_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                        verbose_name="Pontuação de Confiabilidade",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductStockHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Compra"),
                            ("SALE", "Venda"),
                            ("ADJUSTMENT", "Ajuste"),
                            ("LOSS", "Perda"),
                            ("RETURN", "Devolução"),
                        ],
                        max_length=10,
                        verbose_name="Operação",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantidade")),
                (
                    "previous_stock",
                    models.IntegerField(verbose_name="Estoque Anterior"),
                ),
                ("new_stock", models.IntegerField(verbose_name="Novo Estoque")),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Preço Unitário",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "game_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Data do Jogo"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="game.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Estoque",
                "verbose_name_plural": "Históricos de Estoque",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="game.supplier",
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="game_produc_categor_25bd50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["supplier", "is_active"], name="game_produc_supplie_b0bf40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["current_stock"], name="game_produc_current_e7e958_idx"
            ),
        ),
    ]
