# Generated by Django 4.2.24 on 2025-09-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_product_supplier_productstockhistory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supermarketbalance",
            name="game_session",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="profit_margin_max",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="profit_margin_min",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="seasonal_demand_multiplier",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="shelf_life_max",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="shelf_life_min",
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="color",
            field=models.CharField(default="#10B981", max_length=7, verbose_name="Cor"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="icon",
            field=models.CharField(default="📦", max_length=50, verbose_name="Ícone"),
        ),
        migrations.DeleteModel(
            name="BalanceHistory",
        ),
        migrations.DeleteModel(
            name="SupermarketBalance",
        ),
    ]
