# Generated by Django 4.2.24 on 2025-09-24 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_supermarketbalance_game_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="auto_sales_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Vendas Automáticas Habilitadas"
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="daily_sales_target",
            field=models.IntegerField(
                default=40, verbose_name="Meta de Vendas Diárias"
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="time_acceleration",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10080),
                ],
                verbose_name="Aceleração do Tempo (minutos por dia)",
            ),
        ),
    ]
