# Generated by Django 4.2.24 on 2025-09-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_gamesession_auto_sales_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Não Iniciado"),
                    ("ACTIVE", "Ativo"),
                    ("PAUSED", "Pausado"),
                    ("COMPLETED", "Completado"),
                    ("FAILED", "Falhou"),
                ],
                default="NOT_STARTED",
                max_length=12,
                verbose_name="Status do Jogo",
            ),
        ),
    ]
