# Generated by Django 4.2.24 on 2025-09-25 01:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_alter_gamesession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="time_acceleration",
            field=models.IntegerField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10080),
                ],
                verbose_name="Aceleração do Tempo (segundos por dia)",
            ),
        ),
        migrations.CreateModel(
            name="RealtimeSale",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("quantity", models.IntegerField(verbose_name="Quantidade Vendida")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Total"
                    ),
                ),
                ("sale_time", models.DateTimeField(verbose_name="Horário da Venda")),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_sales",
                        to="game.gamesession",
                        verbose_name="Sessão de Jogo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.product",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda em Tempo Real",
                "verbose_name_plural": "Vendas em Tempo Real",
                "ordering": ["-sale_time"],
            },
        ),
    ]
