# Generated by Django 4.2.24 on 2025-09-25 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_gamesession_time_acceleration_realtimesale"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="current_day_sales_count",
            field=models.IntegerField(default=0, verbose_name="Vendas do Dia Atual"),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="last_sales_reset_date",
            field=models.DateField(
                default=datetime.date.today,
                verbose_name="Última Data de Reset de Vendas",
            ),
        ),
    ]
