# Generated by Django 4.2.24 on 2025-09-25 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_gamesession_current_day_sales_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimesale",
            name="game_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data do Jogo"
            ),
        ),
        migrations.AddField(
            model_name="realtimesale",
            name="game_time",
            field=models.TimeField(default="00:00:00", verbose_name="Hora do Jogo"),
        ),
    ]
