# Generated by Django 4.2.24 on 2025-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_realtimesale_game_date_realtimesale_game_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="paused_day_seconds",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Segundos Decorridos no Dia Quando Pausado",
            ),
        ),
    ]
