# Generated by Django 4.2.24 on 2025-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_gamesession_paused_day_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamesession",
            name="paused_day_seconds",
        ),
        migrations.AddField(
            model_name="gamesession",
            name="paused_game_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora do Jogo quando Pausado"
            ),
        ),
    ]
