# Generated by Django 4.2.24 on 2025-10-04 01:19

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePosition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Cargo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Salário Base",
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Salário Mínimo",
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Salário Máximo",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("VENDAS", "Vendas"),
                            ("ESTOQUE", "Estoque"),
                            ("CAIXA", "Caixa"),
                            ("GERENCIA", "Gerência"),
                            ("LIMPEZA", "Limpeza"),
                            ("SEGURANCA", "Segurança"),
                            ("RH", "Recursos Humanos"),
                        ],
                        max_length=50,
                        verbose_name="Departamento",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("payment_month", models.DateField(verbose_name="Mês de Pagamento")),
                (
                    "total_employees",
                    models.IntegerField(verbose_name="Total de Funcionários"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Total Pago"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Processado em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Empregador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Pagamentos",
                "verbose_name_plural": "Históricos de Pagamentos",
                "ordering": ["-payment_month"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Salário",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Data de Contratação"
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("INACTIVE", "Inativo"),
                            ("ON_LEAVE", "Afastado"),
                            ("TERMINATED", "Demitido"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Demissão"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="employees.employeeposition",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Empregador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "ordering": ["name"],
                "unique_together": {("user", "cpf")},
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("payment_month", models.DateField(verbose_name="Mês de Pagamento")),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salário Base"
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Horas Extras",
                    ),
                ),
                (
                    "overtime_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valor Horas Extras",
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Bônus",
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Descontos",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="employees.employee",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folha de Pagamento",
                "verbose_name_plural": "Folhas de Pagamento",
                "ordering": ["-payment_month", "employee__name"],
                "unique_together": {("employee", "payment_month")},
            },
        ),
    ]
